/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import AESPASS.AESPass;
import DAOACCOUNTANDSEVER.Account;
import DAOACCOUNTANDSEVER.AccountXML;
import ModelAndSever2.Xe;
import ModelAndSever2.XeDAO;
import java.io.IOException;
import java.net.MalformedURLException;
import java.util.Date;
import java.rmi.Naming;
import java.rmi.NotBoundException;
import java.rmi.RemoteException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author HP
 */
public class Quanlibaido extends javax.swing.JFrame {

    /**
     * Creates new form Quanlibaido
     */
    public Quanlibaido() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        TFTenKhachHang = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TFBienSoXe = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ComboBoxLoaiXe = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        TFTenBaoVe = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        BTNThem = new javax.swing.JButton();
        BTNSua = new javax.swing.JButton();
        BTNXoa = new javax.swing.JButton();
        BTNTimKiem = new javax.swing.JButton();
        BTNHienThi = new javax.swing.JButton();
        BTNAcccount = new javax.swing.JButton();
        BTNMoChat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("QUẢN LÍ BÃI ĐỖ XE ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên khách hàng", "Biển số xe ", "Loại Xe", "Tên bảo vệ", "Giờ vào bãi"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("Tên khách hàng ");

        jLabel3.setText("Biển số xe");

        TFBienSoXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFBienSoXeActionPerformed(evt);
            }
        });

        jLabel4.setText("Loại xe");

        ComboBoxLoaiXe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mô tô", "Ô Tô", "Xe đạp, thô sơ", " " }));
        ComboBoxLoaiXe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxLoaiXeActionPerformed(evt);
            }
        });

        jLabel5.setText("Tên bảo vệ");

        jLabel6.setText("Giờ vào cổng ");

        jLabel7.setText("Hệ thống tự cập nhật");

        BTNThem.setText("Thêm");
        BTNThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNThemActionPerformed(evt);
            }
        });

        BTNSua.setText("Sửa");
        BTNSua.setFocusPainted(false);
        BTNSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSuaActionPerformed(evt);
            }
        });

        BTNXoa.setText("Xóa");
        BTNXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNXoaActionPerformed(evt);
            }
        });

        BTNTimKiem.setText("Tìm kiếm");
        BTNTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNTimKiemActionPerformed(evt);
            }
        });

        BTNHienThi.setText("Hiển thị");
        BTNHienThi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHienThiActionPerformed(evt);
            }
        });

        BTNAcccount.setText("Account");
        BTNAcccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNAcccountActionPerformed(evt);
            }
        });

        BTNMoChat.setText("Mở chat");
        BTNMoChat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNMoChatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BTNThem, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(64, 64, 64)
                                        .addComponent(BTNSua, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(15, 15, 15))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TFTenKhachHang)
                                            .addComponent(TFTenBaoVe, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(TFBienSoXe)
                                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(37, 37, 37)
                                        .addComponent(BTNXoa, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(BTNTimKiem)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(45, 45, 45)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ComboBoxLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(60, 60, 60)
                                        .addComponent(BTNHienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(BTNAcccount, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(BTNMoChat, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 30, Short.MAX_VALUE))
                    .addComponent(jSeparator1)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TFBienSoXe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(TFTenKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4)
                        .addComponent(ComboBoxLoaiXe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TFTenBaoVe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTNThem)
                    .addComponent(BTNSua)
                    .addComponent(BTNXoa)
                    .addComponent(BTNTimKiem)
                    .addComponent(BTNHienThi)
                    .addComponent(BTNAcccount)
                    .addComponent(BTNMoChat))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TFBienSoXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFBienSoXeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFBienSoXeActionPerformed

    private void ComboBoxLoaiXeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxLoaiXeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxLoaiXeActionPerformed

    private void BTNSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSuaActionPerformed
        // TODO add your handling code here:      
        String BienSo = TFBienSoXe.getText();
        String LoaiXe = ComboBoxLoaiXe.getSelectedItem().toString();
        String TenKhachHang = TFTenKhachHang.getText();
        String TenBaoVe = TFTenBaoVe.getText();
        
        try {
            if(TFBienSoXe.getText().equals("") || TFTenBaoVe.getText().equals("") ||  TFTenKhachHang.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
            }
            else {
                XeDAO xedao = (XeDAO) Naming.lookup("rmi://localhost:500/XeSever");
                xedao.update(BienSo, LoaiXe, TenKhachHang, TenBaoVe);
                JOptionPane.showMessageDialog(this, "Sửa thành công");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_BTNSuaActionPerformed

    private void BTNTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNTimKiemActionPerformed
        // TODO add your handling code here:
                String BienSo = TFBienSoXe.getText();
        try {
            if(TFBienSoXe.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin biển số để tìm kiếm");
            }
            else {
            XeDAO xedao = (XeDAO) Naming.lookup("rmi://localhost:500/XeSever");      
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setColumnIdentifiers(new Object[] {
                "Tên Khách Hàng", "Biển số xe", "Loại xe", "Giờ vào bãi", "Tên bảo vệ"
            });
            model.setRowCount(0);
            Xe xe = xedao.find(BienSo);
            model.addRow(new Object[] {
                 xe.getTenKhachHang(), xe.getBienSo(), xe.getLoaiXe(), xe.getGioVaoBai(), xe.getTenBaoVe()
            });        
            }

        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(Quanlibaido.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Không tìm được xe mong muốn");
        }
        
    }//GEN-LAST:event_BTNTimKiemActionPerformed

    private void BTNThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNThemActionPerformed
        // TODO add your handling code here:
        Date date=java.util.Calendar.getInstance().getTime();      
        String BienSo = TFBienSoXe.getText();
        String LoaiXe = ComboBoxLoaiXe.getSelectedItem().toString();
        String TenKhachHang = TFTenKhachHang.getText();
        String GioVaoBai = date.toString();
        String TenBaoVe = TFTenBaoVe.getText();
        
        try {
            if(TFBienSoXe.getText().equals("") || TFTenBaoVe.getText().equals("") ||  TFTenKhachHang.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin");
            }
            else {
                XeDAO xedao = (XeDAO) Naming.lookup("rmi://localhost:500/XeSever");
                xedao.insert(BienSo, LoaiXe, TenKhachHang, GioVaoBai, TenBaoVe);
                JOptionPane.showMessageDialog(this, "Thêm thành công");
            }
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, e, "Error", JOptionPane.ERROR_MESSAGE);
        } 
        
        
    }//GEN-LAST:event_BTNThemActionPerformed

    private void BTNHienThiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHienThiActionPerformed
        try {
            XeDAO xedao = (XeDAO) Naming.lookup("rmi://localhost:500/XeSever");
            ArrayList<Xe> list = new ArrayList<>();
            list = xedao.show();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setColumnIdentifiers(new Object[] {
                "Tên Khách Hàng", "Biển số xe", "Loại xe", "Giờ vào bãi", "Tên bảo vệ"
            });
            model.setRowCount(0);
            for (Xe xe : list) {
                model.addRow(new Object[] {
                   xe.getTenKhachHang(), xe.getBienSo(), xe.getLoaiXe(), xe.getGioVaoBai(), xe.getTenBaoVe()
                });
            }
            // TODO add your handling code here:

        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(Quanlibaido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTNHienThiActionPerformed

    private void BTNXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNXoaActionPerformed
        // TODO add your handling code here:
        String BienSo = TFBienSoXe.getText();
        try {
            if(TFBienSoXe.getText().equals("")) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập thông tin biển số để xóa");
            }
            else {
            XeDAO xedao = (XeDAO) Naming.lookup("rmi://localhost:500/XeSever");      
            xedao.delete(BienSo);
            JOptionPane.showMessageDialog(this, "Đã xóa!!!!!!!!");            
            }

        } catch (NotBoundException | MalformedURLException | RemoteException ex) {
            Logger.getLogger(Quanlibaido.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTNXoaActionPerformed

    private void BTNAcccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNAcccountActionPerformed
        // TODO add your handling code here:
        ArrayList<Account> list = new ArrayList<>();
        AccountXML accXML = new AccountXML();
        AESPass aes = new AESPass("lvvclvvclvvclvvc");
        try {
            list =  accXML.showXML();
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            model.setColumnIdentifiers(new Object[] {
                "Tên Tài Khoản", "Mật khẩu đã mã hóa", "Mật khẩu chưa mã hóa"
            });
            model.setRowCount(0);
            for(Account acc : list) {
                model.addRow(new Object[]{
                    acc.getTenDangNhap(), acc.getMatKhau(), aes.Decryp(acc.getMatKhau())
                });
            }
        } catch (ParserConfigurationException | SAXException | IOException ex) {
            Logger.getLogger(Quanlibaido.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Quanlibaido.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_BTNAcccountActionPerformed

    private void BTNMoChatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNMoChatActionPerformed
        // TODO add your handling code here:
        			HoiChat jframe3 = new HoiChat();
				try {
					UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
					jframe3.setLocationRelativeTo(null);
					jframe3.setSize(400, 300);
					jframe3.setVisible(true);
                                        
				} catch (ClassNotFoundException | InstantiationException | IllegalAccessException
						| UnsupportedLookAndFeelException e1) {
					// TODO Auto-generated catch block
					e1.printStackTrace();
				}
    }//GEN-LAST:event_BTNMoChatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Quanlibaido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Quanlibaido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Quanlibaido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Quanlibaido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Quanlibaido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNAcccount;
    private javax.swing.JButton BTNHienThi;
    private javax.swing.JButton BTNMoChat;
    private javax.swing.JButton BTNSua;
    private javax.swing.JButton BTNThem;
    private javax.swing.JButton BTNTimKiem;
    private javax.swing.JButton BTNXoa;
    private javax.swing.JComboBox<String> ComboBoxLoaiXe;
    private javax.swing.JTextField TFBienSoXe;
    private javax.swing.JTextField TFTenBaoVe;
    private javax.swing.JTextField TFTenKhachHang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
